apiVersion: v1
kind: Secret
metadata:
  name: workload-east-secret
  namespace: argocd
  labels:
    # This label is the "magic" that tells ArgoCD this is a cluster
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: workload-east
  # patch the following with fresh token 
  server: https://workload-east-control-plane:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IktjUENzSzI4MXFJVEtVVXNnTFozazJ6SmM5SjlDYVdvVFo3QkNwVnlYWVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtbWFuYWdlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY0ZjhhYTE5LTBlYTctNDNjYi04ZjhlLTU3MDZlNjlmMGUxMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcmdvY2QtbWFuYWdlciJ9.DqoRdngArkXdp_L7qfTih7L9hiR09Be4u_xU9aIjkSLFb1S8q97t9USb7n623bl19FG4eYN30cXHSCYBNjw7q_LmH-n5VxQF-8LuTbdup37XzX1nqa4zcPx6je4ONOp0squJRMPuz1S4hwF2MP2oGkPUABfLxYgDYvDCdS3yQw5FiC_ZWEPvPrVM6BU_jcvuzQHDPm2zZDQ5m_JHMWEPHpPEdIvQ0jMoEaaiUQL71Mcag0AUWb5mv_USrGospspxJOtJIZ11QsvWKdhlWKpzxnNGcdIfFP6rkn_gHDjOA5_onxUrJv8mSgeqOjDTtCInrW1tpH41mK-LPIv0DIL3Qw",
      "tlsClientConfig": {
        "insecure": true
      }
    }
