apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-app-ingress 
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: podinfo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  http-app-service
            port:
              number: 80
